sentry:
    dsn: '%env(SENTRY_DSN)%'
    messenger:
        enabled: true # flushes Sentry messages at the end of each message handling
        capture_soft_fails: true # captures exceptions marked for retry too
    options:
        environment: '%kernel.environment%'
        release: '%env(string:key:version:json:file:COMPOSER_JSON)%'
